# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio-joel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafio-joel

  target 'desafio-joelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafio-joelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
